//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trackvisualizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trackvisualizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to ASTER ({0})....
        /// </summary>
        public static string AsterTileLocal_DownloadAndUnpack_ConnectingToAsterServer {
            get {
                return ResourceManager.GetString("AsterTileLocal_DownloadAndUnpack_ConnectingToAsterServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading tile {0} Kb / {1} kB.
        /// </summary>
        public static string AsterTileLocal_DownloadAndUnpack_LoadingTileFormatted {
            get {
                return ResourceManager.GetString("AsterTileLocal_DownloadAndUnpack_LoadingTileFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string AsterTileLocal_DownloadAndUnpack_Ready {
            get {
                return ResourceManager.GetString("AsterTileLocal_DownloadAndUnpack_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking....
        /// </summary>
        public static string AsterTileLocal_DownloadAndUnpack_UnpackingFormatted {
            get {
                return ResourceManager.GetString("AsterTileLocal_DownloadAndUnpack_UnpackingFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found file{0}, using as preloaded GEOTIFF.
        /// </summary>
        public static string AsterTileLocal_DownloadAndUnpack_UsingExistingGeotiffFormatted {
            get {
                return ResourceManager.GetString("AsterTileLocal_DownloadAndUnpack_UsingExistingGeotiffFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorWindow_Error {
            get {
                return ResourceManager.GetString("ErrorWindow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPX Gps Exchange format.
        /// </summary>
        public static string GpxLoaderMiddleware_Description {
            get {
                return ResourceManager.GetString("GpxLoaderMiddleware_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing sources for heightmaps download.
        /// </summary>
        public static string HeightmapDownloaderVm_Initialize_ErrorNoSourcesFound {
            get {
                return ResourceManager.GetString("HeightmapDownloaderVm_Initialize_ErrorNoSourcesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select download source.
        /// </summary>
        public static string HeightmapDownloaderVm_StartDownloadAsync_SelectSource {
            get {
                return ResourceManager.GetString("HeightmapDownloaderVm_StartDownloadAsync_SelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string HeightmapDownloaderWindow_Cancel {
            get {
                return ResourceManager.GetString("HeightmapDownloaderWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heightmap provider.
        /// </summary>
        public static string HeightmapDownloaderWindow_HeightmapProvider {
            get {
                return ResourceManager.GetString("HeightmapDownloaderWindow_HeightmapProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string HeightmapDownloaderWindow_Load {
            get {
                return ResourceManager.GetString("HeightmapDownloaderWindow_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRTM source URL template.
        /// </summary>
        public static string HeightmapDownloaderWindow_SrtmTemplate {
            get {
                return ResourceManager.GetString("HeightmapDownloaderWindow_SrtmTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heightmap download.
        /// </summary>
        public static string HeightmapDownloaderWindow_WindowTitle {
            get {
                return ResourceManager.GetString("HeightmapDownloaderWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report based on track {0}.
        /// </summary>
        public static string HtmlReportExporter_BuildHtml_ReportTitleTemplateFormatted {
            get {
                return ResourceManager.GetString("HtmlReportExporter_BuildHtml_ReportTitleTemplateFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string HtmlReportExporter_Description {
            get {
                return ResourceManager.GetString("HtmlReportExporter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation gain, m.
        /// </summary>
        public static string HtmlReportExporter_Export_AscentHeader {
            get {
                return ResourceManager.GetString("HtmlReportExporter_Export_AscentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation loss, m.
        /// </summary>
        public static string HtmlReportExporter_Export_DescentHeader {
            get {
                return ResourceManager.GetString("HtmlReportExporter_Export_DescentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum height, m.
        /// </summary>
        public static string HtmlReportExporter_Export_MaxHeightHeader {
            get {
                return ResourceManager.GetString("HtmlReportExporter_Export_MaxHeightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance, km.
        /// </summary>
        public static string HtmlReportExporter_Export_SectionDistanceHeader {
            get {
                return ResourceManager.GetString("HtmlReportExporter_Export_SectionDistanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string HtmlReportExporter_Export_SectionNameHeader {
            get {
                return ResourceManager.GetString("HtmlReportExporter_Export_SectionNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string HtmlReportExporter_Export_SectionNumHeader {
            get {
                return ResourceManager.GetString("HtmlReportExporter_Export_SectionNumHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel totals.
        /// </summary>
        public static string HtmlReportExporter_Export_TotalsRowLabel {
            get {
                return ResourceManager.GetString("HtmlReportExporter_Export_TotalsRowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel time, h.
        /// </summary>
        public static string HtmlReportExporter_Export_TravelTimeHeader {
            get {
                return ResourceManager.GetString("HtmlReportExporter_Export_TravelTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KML Keyhole Markup Language.
        /// </summary>
        public static string KmlLoaderMiddleware_Description {
            get {
                return ResourceManager.GetString("KmlLoaderMiddleware_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation profile.
        /// </summary>
        public static string MainWindow_HeightmapHeader {
            get {
                return ResourceManager.GetString("MainWindow_HeightmapHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open track file.
        /// </summary>
        public static string MainWindow_LoadButtonTitle {
            get {
                return ResourceManager.GetString("MainWindow_LoadButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download heightmaps.
        /// </summary>
        public static string MainWindow_LoadHeightmaps_Label {
            get {
                return ResourceManager.GetString("MainWindow_LoadHeightmaps_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string MainWindow_LoadingLabel {
            get {
                return ResourceManager.GetString("MainWindow_LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load track.
        /// </summary>
        public static string MainWindow_LoadTrackLabel {
            get {
                return ResourceManager.GetString("MainWindow_LoadTrackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain per day, m.
        /// </summary>
        public static string MainWindow_Route_AscentHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_AscentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpack weight F, kg.
        /// </summary>
        public static string MainWindow_Route_BackpackWeightFHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_BackpackWeightFHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpack weight M, kg.
        /// </summary>
        public static string MainWindow_Route_BackpackWeightMHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_BackpackWeightMHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation delta sum, m.
        /// </summary>
        public static string MainWindow_Route_DeltaHeightHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_DeltaHeightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation loss, m.
        /// </summary>
        public static string MainWindow_Route_DescentHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_DescentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance, km.
        /// </summary>
        public static string MainWindow_Route_DistanceHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_DistanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MainWindow_Route_ExportLabel {
            get {
                return ResourceManager.GetString("MainWindow_Route_ExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIETS Index.
        /// </summary>
        public static string MainWindow_Route_FietsHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_FietsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep height, m.
        /// </summary>
        public static string MainWindow_Route_FinHeightHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_FinHeightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heightmaps missing.
        /// </summary>
        public static string MainWindow_Route_HeightmapsMissingLabel {
            get {
                return ResourceManager.GetString("MainWindow_Route_HeightmapsMissingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum height, m.
        /// </summary>
        public static string MainWindow_Route_MaxHeightHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_MaxHeightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main heights, m.
        /// </summary>
        public static string MainWindow_Route_NotableHeightsHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_NotableHeightsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string MainWindow_Route_SectionHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string MainWindow_Route_SectionNumHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_SectionNumHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel time, h.
        /// </summary>
        public static string MainWindow_Route_TimeHeader {
            get {
                return ResourceManager.GetString("MainWindow_Route_TimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string MainWindow_RouteHeader {
            get {
                return ResourceManager.GetString("MainWindow_RouteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel planning.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsWindow_Cancel {
            get {
                return ResourceManager.GetString("SettingsWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsWindow_Language {
            get {
                return ResourceManager.GetString("SettingsWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsWindow_Save {
            get {
                return ResourceManager.GetString("SettingsWindow_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program settings.
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRTM.
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_Description {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.hgt, cleaning up voids... .
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_CleanupActionFormatted {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_CleanupActionFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}....
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_DownloadingFormatted {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_DownloadingFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔘 Server doesn&apos;t have SRTMs for this region.
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_E404NoSrtmOnServer {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_E404NoSrtmOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔘 Invalid server address in loader window.
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_E404ServerAddrInvalid {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_E404ServerAddrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔘 Server address obsolete, you have to look for fresh one.
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_E404ServerAddrObsolete {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_E404ServerAddrObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote server responded with 404 (not found). Cause could be:.
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_Error404Reasons {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_Error404Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - .hgt file missing in archive, something is wrong.
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_ErrorNoHgtFileInArchive {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_ErrorNoHgtFileInArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ready. .
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_HeightmapReadyFormatted {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_HeightmapReadyFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0:0.0} Kb....
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_LoadProgressFormatted {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_LoadProgressFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing height-correction utility `{0}`.
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_SrtmInterpNotFound {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_SrtmInterpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error unpacking: `{0}`! File {1} loaded, but you have to unpack it manually.
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_UnpackingErrorFormatted_ManualActionRequired {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_UnpackingErrorFormatted_Manua" +
                        "lActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking {0}.
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_DownloadHeightmap_UnpackingFormatted {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_DownloadHeightmap_UnpackingFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errror: .
        /// </summary>
        public static string SrtmFileDownloadHeightmapProvider_ExecuteCommandAsync_ErrorGeneral {
            get {
                return ResourceManager.GetString("SrtmFileDownloadHeightmapProvider_ExecuteCommandAsync_ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish {0:0.} Km.
        /// </summary>
        public static string TrackChartVm_GetSectionLabel_FinishFormatted {
            get {
                return ResourceManager.GetString("TrackChartVm_GetSectionLabel_FinishFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string TrackChartVm_TrackChartVm_HeightSeriesTitle {
            get {
                return ResourceManager.GetString("TrackChartVm_TrackChartVm_HeightSeriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string TrackChartVm_TrackChartVm_SectionSeriesTitle {
            get {
                return ResourceManager.GetString("TrackChartVm_TrackChartVm_SectionSeriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.} Km.
        /// </summary>
        public static string TrackChartVm_XFormatter_ChartSubscriptLengthFormatted {
            get {
                return ResourceManager.GetString("TrackChartVm_XFormatter_ChartSubscriptLengthFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.} m.
        /// </summary>
        public static string TrackChartVm_YFormatter_ChartSubscriptHeightFormatted {
            get {
                return ResourceManager.GetString("TrackChartVm_YFormatter_ChartSubscriptHeightFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No loader middleware!.
        /// </summary>
        public static string TrackManagerVm_LoadTrackFromFileAsync_No_loader_middleware {
            get {
                return ResourceManager.GetString("TrackManagerVm_LoadTrackFromFileAsync_No_loader_middleware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supply stash is placed before route start.
        /// </summary>
        public static string TrackReportItemVm_Comment_DropBeforeStart {
            get {
                return ResourceManager.GetString("TrackReportItemVm_Comment_DropBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaving supply stash.
        /// </summary>
        public static string TrackReportItemVm_Comment_LeavingDrop {
            get {
                return ResourceManager.GetString("TrackReportItemVm_Comment_LeavingDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picking supply stash.
        /// </summary>
        public static string TrackReportItemVm_Comment_PickingDrop {
            get {
                return ResourceManager.GetString("TrackReportItemVm_Comment_PickingDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string TrackReportItemVm_NextSectionName_StubFinishName {
            get {
                return ResourceManager.GetString("TrackReportItemVm_NextSectionName_StubFinishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string TrackReportItemVm_SectionStartName_StubStartName {
            get {
                return ResourceManager.GetString("TrackReportItemVm_SectionStartName_StubStartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating elevation delta.
        /// </summary>
        public static string TrackReportVm_CreateReportAsync_DeltaCalculation {
            get {
                return ResourceManager.GetString("TrackReportVm_CreateReportAsync_DeltaCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heightmap &lt;{0}&gt; has invalid values.
        ///Run
        ///srtm_interp {1}
        ///using command line.
        ///Otherwise, you&apos;ll get completely invalid height calculations!.
        /// </summary>
        public static string TrackReportVm_CreateReportAsync_ErrHeightmapInvalid {
            get {
                return ResourceManager.GetString("TrackReportVm_CreateReportAsync_ErrHeightmapInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation stopped due to missing heightmaps.
        /// </summary>
        public static string TrackReportVm_CreateReportAsync_ErrNoHeightmap {
            get {
                return ResourceManager.GetString("TrackReportVm_CreateReportAsync_ErrNoHeightmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough points in track.
        /// </summary>
        public static string TrackReportVm_CreateReportAsync_ErrNoPointsInTrack {
            get {
                return ResourceManager.GetString("TrackReportVm_CreateReportAsync_ErrNoPointsInTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough waypoints to split track.
        /// </summary>
        public static string TrackReportVm_CreateReportAsync_ErrNotEnoughPoints {
            get {
                return ResourceManager.GetString("TrackReportVm_CreateReportAsync_ErrNotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track not loaded.
        /// </summary>
        public static string TrackReportVm_CreateReportAsync_ErrNoTrack {
            get {
                return ResourceManager.GetString("TrackReportVm_CreateReportAsync_ErrNoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empy track split! Couldnt split track to day sections.
        /// </summary>
        public static string TrackReportVm_CreateReportAsync_ErrSplitEmptyCantContinue {
            get {
                return ResourceManager.GetString("TrackReportVm_CreateReportAsync_ErrSplitEmptyCantContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refining track split.
        /// </summary>
        public static string TrackReportVm_CreateReportAsync_RefiningSplit {
            get {
                return ResourceManager.GetString("TrackReportVm_CreateReportAsync_RefiningSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting track to day sections.
        /// </summary>
        public static string TrackReportVm_CreateReportAsync_SplittingTrack {
            get {
                return ResourceManager.GetString("TrackReportVm_CreateReportAsync_SplittingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report exporter with ID {0} unknown.
        /// </summary>
        public static string TrackReportVm_ExportReportAsync_Err_Report_exporter_with_ID__0__unknown {
            get {
                return ResourceManager.GetString("TrackReportVm_ExportReportAsync_Err_Report_exporter_with_ID__0__unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select report format.
        /// </summary>
        public static string TrackReportVm_ExportReportAsync_Select_report_format {
            get {
                return ResourceManager.GetString("TrackReportVm_ExportReportAsync_Select_report_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All SRTM files loaded OK!.
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_AllHeightmapsLoadedOk {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_AllHeightmapsLoadedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They have to be loaded from NASA server or similiar source.
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_ErrHeightmapDownloadRequired {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_ErrHeightmapDownloadRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following SRTMs are found missing during load:.
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_ErrHeightmapsMissing {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_ErrHeightmapsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading file!.
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_GeneralErrDuringFileLoad {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_GeneralErrDuringFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track requires heightmaps .
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_HeightmapsRequired {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_HeightmapsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading heightmaps (SRTM).
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_LoadingHeightmap {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_LoadingHeightmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading files....
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_LoadingHeightmaps {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_LoadingHeightmaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glueing {0} tracks.
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_MergingTracksFormatted {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_MergingTracksFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One track loaded.
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_SingleTrackLoaded {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_SingleTrackLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track loaded successfully.
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_TrackLoadedOk {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_TrackLoadedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No track in file!.
        /// </summary>
        public static string TrackVm_LoadTracksFromFile_TrackNotFound {
            get {
                return ResourceManager.GetString("TrackVm_LoadTracksFromFile_TrackNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} waypoints.
        /// </summary>
        public static string TrackVm_ValidateSlicepoints_FoundNSlicepointsFormatted {
            get {
                return ResourceManager.GetString("TrackVm_ValidateSlicepoints_FoundNSlicepointsFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected track doesnt have enough waypoints to split by day sections! You have to specify waypoint source additionally, or resave selected track file with waypoints included..
        /// </summary>
        public static string TrackVm_ValidateSlicepoints_NotEnoughSlicepoints {
            get {
                return ResourceManager.GetString("TrackVm_ValidateSlicepoints_NotEnoughSlicepoints", resourceCulture);
            }
        }
    }
}
